spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: my_user
    password: password123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8180