spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/users
    username: my_user
    password: my_password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8180