spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8180