spring:
  datasource:
    url: jdbc:postgresql://54.221.153.51:5432/users
    username: postgres
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8180